# Generated by Django 5.2.12 on 2026-03-12 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, unique=True)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('floor', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['floor', 'slot_number'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('mini', 'Mini / Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('jeep', 'Jeep'), ('muv', 'MUV / Van'), ('truck', 'Truck / Pickup')], default='sedan', max_length=10)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingslot')),
            ],
        ),
    ]
